### ISSUE TITLE
tricky metro configuration error

### ISSUE THREAD

**Issue by sallespro** [sAleksovski/react-native-android-widget#1]
i would prefer the example to be a completely independent repo.

```
error: Error: Unable to resolve module @babel/runtime/helpers/interopRequireDefault from /Users/rrocsal/dev/code/research/react-native-android-widget/src/api/register-widget-task-handler.tsx: @babel/runtime/helpers/interopRequireDefault could not be found within the project or in these directories:
  ../../../../../node_modules
```

**Comment by sAleksovski** [comment]
I prefer the example to be in the same repo as the library, because I can use it to test it.

I'm not sure how you are starting the example app, but I cloned it again and did a fresh install, and it works.

```sh
git clone https://github.com/sAleksovski/react-native-android-widget.git
cd react-native-android-widget
yarn install
cd example
yarn install
yarn android && yarn start
```

**Comment by sallespro** [comment]
hello Stefan, thanks for checking this.
From my perspective, examples should be independent because we use it as starters, boilerplates sometimes, and it was a major problem for me to understand this
In `metro.config.js`

```
const pak = require('../package.json');

const root = path.resolve(__dirname, '..');

const modules = Object.keys({
  ...pak.peerDependencies,
});
``` 
what is necessary to do to make it `independent` from the main repo ?

**Comment by sAleksovski** [comment]
You don't need to make any changes to `metro.config.js` to use the library.

The file you referenced is only used for the example app, so that it can import the library from the same repo, and not from npm.

To use the library in your project you can follow the docs, and the tutorial inside them explaining how to create a widget step by step.

https://saleksovski.github.io/react-native-android-widget/docs/
