### ISSUE TITLE
Touch is not hitting the right element on real device

### ISSUE THREAD

**Issue by mark-yacoub** [sAleksovski/react-native-android-widget#20]
Hi, I'm using the widget on a Pixel 6 device.
I'm noticing that when i touch an element that accepts a click, the touch area highlighted is off the actual element. 
this behavior doesn't happen on the emulator
I noticed that it's slightly better if i wrap a text or an icon inside a flex and the flex accepts the touch instead of icon or text.
here is my code
```
      <FlexWidget key={task.id + taskCompleted} style={styles.taskRowContainer}>
        <FlexWidget style={{borderLeftWidth: 2, borderLeftColor: taskColor, paddingLeft: 10}}>
          <TextWidget text={task.name} style={{fontSize: 16}} />
          <TextWidget text={task.type} style={{fontSize: 13, color: taskColor}} />
        </FlexWidget>
        <FlexWidget
          clickAction={ACTIONS.TOGGLE_TASK}
          clickActionData={{
            shouldMarkComplete: !taskCompleted,
            taskId: task.id,
            date: date.toString(),
            userId,
          }}>
          <IconWidget
            font='MaterialIcons-Regular'
            icon={taskCompleted ? 'check_circle' : 'radio_button_unchecked'}
            size={36}
            style={{color: taskCompleted ? colors.primaryTriadic2 : colors.inactiveElement}}
          />
        </FlexWidget>
      </FlexWidget>
```

If you wanna test it out, the app was just released the store for our testing
https://play.google.com/store/apps/details?id=com.metanify
      
or you can check this screen recorder (watch where i click and where the click gets registered and highlighted)
https://github.com/sAleksovski/react-native-android-widget/assets/11547193/9ac14244-66cd-4aea-b363-6d6728bec59c

**Comment by sAleksovski** [comment]
I think this works on some launchers, and does not work on others.
The problem is that the launcher sometimes "lies" about the widget size.

![image](https://github.com/sAleksovski/react-native-android-widget/assets/7473800/2c017d1a-34b8-4a20-9f2e-22b4a3d9a739)

![image](https://github.com/sAleksovski/react-native-android-widget/assets/7473800/534f54a0-f3d2-4a0f-aaaa-0f2c5fc259b8)

When inspecting the widget, it's height is 318dp, but Android reports that it is 354dp.

We must know the exact size in order to position everything correctly. Because the generated widget is bigger than the real widget, it gets scaled down and doesn't look right.

I'll try to fix this when I have some time.

**Comment by mark-yacoub** [comment]
Is this what would be causing the widget to get the full width of the grid?

**Comment by sAleksovski** [comment]
I'll close this issue since there was no response.
You can reopen it if the problem is still there.
