### ISSUE TITLE
case "WIDGET_UPDATE" is not working with updatePeriodMillis

### ISSUE THREAD

**Issue by zubyrbutt** [sAleksovski/react-native-android-widget#23]
Hi,

I hope this message finds you well. Firstly, I want to express my gratitude for providing such a comprehensive solution for Android widgets. It has been incredibly helpful. I'm eagerly looking forward to the release of the iOS widget functionality as well.

I have encountered a small issue while implementing the Android widget in my project and was hoping you could assist me. I added the following line to the `widgetprovider_widgetname.xml` file: `android:updatePeriodMillis="1800000"`. This line is meant to set the refresh interval for the widget to 30 minutes.

In addition, I added a console log statement in my `widgetTaskHandler.tsx` file to track the widget updates:
```typescript
case "WIDGET_UPDATE":
  console.log("Widget updated");
  break;
```

However, despite these additions, the widget update is not being triggered every 30 minutes as expected.

I have reviewed my implementation and checked for any potential mistakes, but I have been unable to identify the issue. Could you please lend me a hand and provide some guidance on what I might be missing or what steps I should take to troubleshoot this problem?

Thank you in advance for your assistance. I truly appreciate your support.

Best regards,

**Comment by sAleksovski** [comment]
Hey,

Thanks for the kind words. I guess you figured it out since you closed the issue.
The widget will not be updated exactly after 30 minutes, but it should be close to 30 minutes. It depends on Android.

You can see the exact wording on the [Android docs](https://developer.android.com/reference/android/appwidget/AppWidgetProviderInfo.html#updatePeriodMillis)

If not you can see the `DebugEventsWidget` in the example app, which logs every event from the library.

By the way, I currently have no plans for adding iOS support.
