### ISSUE TITLE
Unable to use ToastAndroid on Widgets on home screen

### ISSUE THREAD

**Issue by Jocabin** [sAleksovski/react-native-android-widget#25]
Everything is on the title of the issue, there is some informations:

- I'm using android 13, on a pixel 5 (real device)
- I've also tried using emulator

There is the line of code I'm using
`ToastAndroid.show('message', ToastAndroid.LONG);`

This line is in my widget task handler file, on the `WIDGET_CLICK` event

let me know if you want more informations, this isthe first time I open an issue

**Comment by sAleksovski** [comment]
Hi,

I'm getting "Suppressing toast from package com.androidwidgetexample by user request." when trying to show a toast from the widget task handler.

I found that message in [NotificationManagerService.java](https://android.googlesource.com/platform/frameworks/base/+/master/services/core/java/com/android/server/notification/NotificationManagerService.java#3379) in the Android code.

I assume that the app needs to be in foreground in order to show Toasts.
