### ISSUE TITLE
Build failed: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.

### ISSUE THREAD

**Issue by MaximCemencov** [sAleksovski/react-native-android-widget#27]
> Configure project :app
 ℹ️  Applying gradle plugin 'expo-dev-launcher-gradle-plugin' (expo-dev-launcher@2.2.1)
[stderr] 
FAILURE: Build completed with 2 failures.
[stderr] 
1: Task failed with an exception.
[stderr] 
* Where:
[stderr] 
Build file '/home/expo/workingdir/build/android/app/build.gradle' line: 21
[stderr] 
* What went wrong:
[stderr] 
A problem occurred evaluating project ':app'.
[stderr] 
> path may not be null or empty string. path=''
[stderr] 
* Try:
[stderr] 
> Run with --stacktrace option to get the stack trace.
[stderr] 
> Run with --info or --debug option to get more log output.
[stderr] 
> Run with --scan to get full insights.
[stderr] 
2: Task failed with an exception.
[stderr] 
-----------
[stderr] 
* What went wrong:
[stderr] 
A problem occurred configuring project ':app'.
[stderr] 
> compileSdkVersion is not specified. Please add it to build.gradle
[stderr] 
* Try:
[stderr] 
> Run with --stacktrace option to get the stack trace.
[stderr] 
> Run with --info or --debug option to get more log output.
[stderr] 
> Run with --scan to get full insights.
[stderr] 
[stderr] 
* Get more help at https://help.gradle.org
[stderr] 
BUILD FAILED in 1m 56s
10 actionable tasks: 10 executed
Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.

Error desc: 
I start the dev build in the expo but in the expo server return me this error
<img width="1188" alt="Screenshot 2023-07-05 at 16 09 15" src="https://github.com/sAleksovski/react-native-android-widget/assets/112812079/f7bf8ced-f6fc-4610-88cc-e1c15f792647">
and i have error in the widget-task-handler
<img width="1728" alt="Screenshot 2023-07-05 at 16 08 57" src="https://github.com/sAleksovski/react-native-android-widget/assets/112812079/54beebf5-49f5-4e1e-b7fb-2dbd365f8f23">

**Comment by sAleksovski** [comment]
Hi,

This does not look like an error with the library. There is already a similar issue on the Expo repo (https://github.com/expo/expo/issues/22584) with the same error message.
Can you try some of the suggested fixes?

As for the error in `widget-task-handler.ts`, it should be `widget-task-handler.tsx` (`tsx` instead of `ts`) so that you can use React Components inside it.
I fixed the docs to use `.tsx` instead of `ts` in the example code.

If you are sure that the issue is with this library you can reopen the issue and share an reproducible example that I can take a look at.
