### ISSUE TITLE
How to create a 2x2 sized widget with a width and height of 1:1, occupying the screen side by side



### ISSUE THREAD

**Issue by A-ANing** [sAleksovski/react-native-android-widget#31]
May I ask? The following two are generated by me, and I want them to be the same as the above two, with the width occupied side by side and the height equal to the width. A normal phone should have two in one row, but if it is a tablet, there may be more than two in one row.

<p align="center">
<img src="https://github.com/sAleksovski/react-native-android-widget/assets/43433064/ebd29d6b-dddc-44d3-b3ad-42a276cbe960"  width="350" >
</p>

**Comment by A-ANing** [comment]
It can be seen that the width of each of the two widgets above is the maximum value, and the height is equal to the width; I don't know how many dps minWidth should be set to achieve such a layout.

**Comment by A-ANing** [comment]
`
   props.renderWidget(<Widget {...widgetInfo}  width={widgetInfo.screenInfo.screenWidthDp/2} />);

`
not work…

**Comment by sAleksovski** [comment]
Can you share the code for your widget?

`widgetInfo.width` will tell you the actual width of the widget that is added on the home screen. You cannot  specify the exact size.

You can only use `minWidth` and `minHeight` (https://saleksovski.github.io/react-native-android-widget/docs/tutorial/register-widget#add-a-widget-provider-xml-file) or if using Expo (https://saleksovski.github.io/react-native-android-widget/docs/tutorial/register-widget-expo#use-config-plugin-in-appjsonconfigjsconfigts). When the widget is added on the home screen, Android will decide the actual height.

If you want your widget to be a square, you can use 

```
<FlexWidget style={{ width: widgetInfo.width, height: widgetInfo.width }}>
  ...
</FlexWidget>
```

You can also read https://developer.android.com/develop/ui/views/appwidgets/layouts for deciding on the `minWidth` and `minHeight`

**Comment by A-ANing** [comment]
![Screenshot_20230721_015057_com.huawei.android.launcher.jpg](https://github.com/sAleksovski/react-native-android-widget/assets/43433064/b486a8ea-5a64-46ff-96cb-abda88f367f7)

Is this the reason? The actual size is always smaller than the box

**Comment by sAleksovski** [comment]
What launcher are you using, and what version of the library are you using?

**Comment by A-ANing** [comment]
Phone Info：
name: huawei mate 40 pro
model: NOH-AN01
version: 11.0.0.192
android version: 10

"react": "18.2.0",
"react-native": "0.72.3",
"react-native-android-widget": "^0.7.0",

**Comment by A-ANing** [comment]
我将RNWidget.java中的以下代码

```
RNWidgetUtil.getWidgetWidth(appContext, widgetId),
RNWidgetUtil.getWidgetHeight(appContext, widgetId)
```         
  ===>          
            
 ```
public void drawWidget(int widgetId) throws Exception {
       ...

        WidgetWithViews widgetWithViews = WidgetFactory.buildWidgetFromRoot(
            appContext,
            configClone,
            180,//RNWidgetUtil.getWidgetWidth(appContext, widgetId),
            180//RNWidgetUtil.getWidgetHeight(appContext, widgetId)
        );
      ...
    }

```

xml:
```
<?xml version="1.0" encoding="utf-8"?>
<appwidget-provider xmlns:android="http://schemas.android.com/apk/res/android"
    android:minWidth="130dp"
    android:minHeight="130dp"
    android:updatePeriodMillis="300000"

    android:initialLayout="@layout/rn_widget"

    android:previewImage="@drawable/demo_preview"

    android:resizeMode="horizontal|vertical"
    android:widgetCategory="home_screen">
</appwidget-provider>
```
## In this way, it can be full, but I don't know java, so I don't know how to get the specific size correctly

This is after changing the java code `WidgetFactory.buildWidgetFromRoot(...)`
![998e8a6e84f44dd0c468a99a241322c](https://github.com/sAleksovski/react-native-android-widget/assets/43433064/511115f0-db4c-43b3-833b-b207e1e95279)



This is not modified before, only the style height under widgets is set to width：
![da6cc9c5b832614ec8abd510d5b2326](https://github.com/sAleksovski/react-native-android-widget/assets/43433064/b8241901-7318-4f2f-96c2-960a71426542)

**Comment by sAleksovski** [comment]
It is not centered because `180` is not the correct width, it's likely it's actually smaller.

But you are right, this looks like one of the previous issues.

The problem is that we cannot render React Native views directly to the widget. What this library does is render the React Native views to an image, and showing that image in the widget.
For it to look good, we need to know the **exact** size of the widget, to create an image with the correct size.

When using some launchers, the reported and actual size are not the same...
See this comment (https://github.com/sAleksovski/react-native-android-widget/issues/20#issuecomment-1583094892) for example.

I haven't found a reliable way to get the **exact** size, the current behavior is to crop the widget if the reported size is smaller.

Can you try with Nova Launcher and see if the widget works?
Still, that is not a solution since you cannot control what launcher your users are using...

**Comment by A-ANing** [comment]
I checked some information, android cannot directly obtain the actual size of the widget on the screen, nor can it obtain the component size of `initialLayout` in `appwidget-provider`;  

The size of the widget is limited by the screen grid, so the actual size may not be equal to the set `minWidth` and `minHeight`, which is really a headache;

**Comment by A-ANing** [comment]
WidgetFactory.buildWidgetFromRoot，Can you skip setting the width and height? I'll make the rn view full

**Comment by sAleksovski** [comment]
No, the parameters are mandatory.

See my previous comment about why (https://github.com/sAleksovski/react-native-android-widget/issues/31#issuecomment-1645023985).

**Comment by sAleksovski** [comment]
I've documented this behavior in https://saleksovski.github.io/react-native-android-widget/docs/limitations, and opened a new issue #34 to track it

**Comment by arhaanb** [comment]
I don't mind the widget being a bit smaller than the actual grid but somehow while using a ListView the content seems to exceed the width of the background rectangle (image attached)

![Screenshot_20240124-154522_One UI Home](https://github.com/sAleksovski/react-native-android-widget/assets/49993666/15d24d82-4232-4b93-b1e2-c9daa3f68793)

I'm not sure how I could make this background extend a little bit in height so that the content doesn't flow out, I think this would make the widget a bit more useful for someone using this particular launcher. I'm testing the widget on the default launcher on OneUI 3.1 (Android 11). 

Thank you for your help!

**Comment by sAleksovski** [comment]
You can try setting background color to the list item.
