### ISSUE TITLE
Widget is lagging after app was killed

### ISSUE THREAD

**Issue by mefjuu** [sAleksovski/react-native-android-widget#33]
I noticed that widget is "slow" after application launched on physical device was killed. I mean e.g. renderWidget() on clickAction is laggy. It seems that it takes 1-3 seconds to instantiate headless task by `registerWidgetTaskHandler()`.

Have you experienced such a behavior? Is there something in app that may impact on this negatively?

Or maybe is it Android memory management related problem?

**Comment by sAleksovski** [comment]
I just tried it on my device, and didn't see any noticeable delay. But it's possible to have some delay when clicking the widget if the app is killed, since then Android needs to handle the click, start the React Native app in background...

I don't see any way to make it faster when the app is killed...
Do you have the delay when the app is active?
