### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by shtrihstr** [sAleksovski/react-native-android-widget#36]
Hello!

Is there a way to update (re-render) a widget on the dark/light mode change?

**Comment by sAleksovski** [comment]
Hi,

I'm not sure if there is a way to know when the dark/light mode is changed while the app is in the background.

I'll investigate when I have some free time.

**Comment by sAleksovski** [comment]
As far as I could find, there is no way to listen to light/dark theme change from the background.
I know some widgets can change their view when dark/light mode is changed, but that is done using separate xml layouts for light and dark mode.
I tried that, but `onUpdate` is never called, so we cannot trigger a rerender of the widget.

I'll close this since it is not possible (or I couldn't find a way), but feel free to reopen it if you find a way and I can try to implement it.
