### ISSUE TITLE
Widget is not rendering

### ISSUE THREAD

**Issue by Rohit3523** [sAleksovski/react-native-android-widget#50]
I followed each step provided in the Tutorial page and the widget is reflecting in widget section but when i add that widget in homescreen, it just show transparent view without any text or anything.

React Native: 0.72.3
react-native-android-widget: 0.8.2

**Comment by Rohit3523** [comment]
Here is the logcat when i place a widget
```
 AndroidRuntime: java.lang.RuntimeException: Unable to instantiate receiver com.minocular.dcw.widget.CBAWidget: java.lang.ClassNotFoundException: Didn't find class "com.minocular.dcw.widget.CBAWidget"```
 
 Receiver
 ```
<receiver
          android:name=".widget.CBAWidget"
          android:exported="false"
          android:label="CBA Widget">
          <intent-filter>
              <action android:name="android.appwidget.action.APPWIDGET_UPDATE" />
              <action android:name="com.minoculardcw.WIDGET_CLICK" />
          </intent-filter>
          <meta-data
              android:name="android.appwidget.provider"
              android:resource="@xml/widgetprovider_cbatrend" />
      </receiver>
```

**Comment by Rohit3523** [comment]
For Hello example, i am getting
```
BroadcastQueue: Unable to launch app com.minocular.dcw/10867 for broadcast Intent { act=android.appwidget.action.APPWIDGET_ENABLED flg=0x10 cmp=com.minocular.dcw/.widget.Hello }: process is bad```

**Comment by sAleksovski** [comment]
I think the error is self-explanatory.

`AndroidRuntime: java.lang.RuntimeException: Unable to instantiate receiver com.minocular.dcw.widget.CBAWidget: java.lang.ClassNotFoundException: Didn't find class "com.minocular.dcw.widget.CBAWidget"`

You don't have a `CBAWidget` class, or it is on the wrong place, or with the wrong name.

Can you go through the tutorial again to see what you missed?

As for the last error, process is bad, I guess it's due to a lot of crashes due to the missing class. You should be able to Google it and find a solution.

**Comment by Rohit3523** [comment]
It was my fault, i mentioned `package com.minoculardcw.widget;` instead of `package com.minocular.dcw.widget;`
