### ISSUE TITLE
no support for device orientation change?

### ISSUE THREAD

**Issue by christian-bechette** [sAleksovski/react-native-android-widget#96]
I installed the demo apk and added the Counter widget to my tablet's home screen. Looks good in portrait, but rotating the tablet in landscape mode results in the widget display being incorrectly sized. Is there a way to handle that in the current code?

![android-widget](https://github.com/user-attachments/assets/de13b5b0-2d94-4927-8af3-6238f0871965)

**Comment by sAleksovski** [comment]
As far as I know this is not possible to achieve by using this library.

This is the same or related to #90 and #36

I'll close this since it is not possible (or I couldn't find a way), but feel free to reopen it if you find a way and I can try to implement it.

**Comment by christian-bechette** [comment]
@sAleksovski A solution could be to specify a `port` and `land` layout for each widget as per https://developer.android.com/guide/topics/resources/providing-resources#AlternativeResources . Looks like it also requires removal of `onConfigurationChanged()` and `android:configChanges` from the manifest. 

Do you think that approach could work?

**Comment by sAleksovski** [comment]
This looks like configuration for an Activity.

I already tried with separate `port` and `land` layout files, but that does not call any method from `AppWidgetProvider`, which is needed in order to update the image.

Regular Android widgets (defined using xml) can be updated because the data does not change, only the layout depending on the `port/land` files, but in this library we are rendering to an image and the layout is the same. We need some method from `AppWidgetProvider` to be called in order to render a new image.
